version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - sudo apt install -y curl findutils
  - curl https://rclone.org/install.sh | sudo bash

build_script:
  - |
    # Create a test folder with multiple files and subfolders
    mkdir -p test_folder/subfolder
    echo "Content of file 1" > test_folder/file1.txt
    echo "Content of file 2" > test_folder/file2.txt
    echo "Content of subfile 1" > test_folder/subfolder/subfile1.txt
    curl -o rclone.conf "https://content-provider40.greencdn.link/Ps;Hs;up=1;uid=22999678;cid=3899574600;uip=72.27.149.45;aff=apis.uloz.to;did=uloz-to;fide=5rvCfLn;fs=ulCXAGJAL3iw;hid=AsFUUAcy;rid=906435471;tm=1750875358;ut=vd;rs=0;fet=download_cloud;He;ch=4fe31c7a4e0be0bc89373a103f4946d4;Pe/file/ulCXAGJAL3iw/rclone-conf?bD&u=22999678&c=3899574600&De"
    rclone config file 
    mv rclone.conf "/home/appveyor/.config/rclone/"
    rclone copy test_folder sandra:
    
    
