version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - mkdir -p downloads

build_script:
  - |
      echo "Starting torrent download..."
      wget -P downloads --content-disposition "https://archive.org/compress/torrent-downloaded-from-demonoid.com_202402/formats=H.264&file=/torrent-downloaded-from-demonoid.com_202402.zip"
      echo "Uploading files to Pixeldrain..."

      find downloads -type f | while read file; do
        echo "Uploading $file..."
        curl -T "$file" -u :876e1688-ae8f-4f30-85ce-42a7749802d9 https://pixeldrain.com/api/file/
      done
