version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

build_script:
  - |
    # Create a test folder with multiple files and subfolders
    mkdir -p test_folder/subfolder
    echo "Content of file 1" > test_folder/file1.txt
    echo "Content of file 2" > test_folder/file2.txt
    echo "Content of subfile 1" > test_folder/subfolder/subfile1.txt

    # Base upload URL
    BASE_URL="https://filebin.net/Sahaujwsh/"

    # Find all files recursively and upload each with filename appended
    find test_folder -type f | while read -r file; do
      filename=$(basename "$file")
      upload_url="${BASE_URL}${filename}"
      echo "Uploading $file to $upload_url..."
      curl -X POST \
        "$upload_url" \
        -H 'accept: application/json' \
        -H 'Content-Type: application/octet-stream' \
        --data-binary "@$file"
    done
