version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - sudo apt install -y curl findutils python3 python3-pip
  - pip install requests requests_toolbelt 

build_script:
  - |
    # Create a test folder with multiple files and subfolders
    mkdir -p downloads/subfolder
    curl -o gigi.py "https://pixeldrain.com/api/file/Eh4nzRBE?download"
    python3 -m gigi.py
    
    
