version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - master  # Trigger only on the master branch, adjust if needed

install:
  - sudo apt-get install -y python3 python3-pip curl git
  - pip install requests  # Install Python dependencies if needed
  - git clone https://github.com/Fash483/fuzzy-pancake
  - cd fuzzy-pancake  # Move into the cloned repository directory

build_script:
  - echo "Creating test files..."
  # Create test files directly
  - echo "This is a test file for Invader ZIM" > "downloads/Invader ZIM - S00E07 - The Music of Zim (1080p x265 EDGE2020).txt"
  - echo "Another test file for Sjsjsnn [EZTVX.TO]" > "downloads/Sjsjsnn [EZTVX.TO].txt"
  
  # Now we will run the Python script to upload the files
  - echo "Uploading files to filebin..."
  - python3 filebin_upload.py  # Run your Python script (adjust if in subfolder)
