version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - sudo apt install -y nodejs npm curl
  - npm install torrent-dl
  - mkdir -p downloads
  - cd downloads

build_script:
  - |
      echo "Starting torrent download..."
      npx torrent-dl -i "magnet:?xt=urn:btih:612A7F4F112B919CEDB99B3AF0879F59E6B9C021&dn=Squid.Game.S03.1080p.NF.WEB-DL.DUAL.DDP5.1.Atmos.H.265-Spidey%20%20%20%20%20%20%20%20&tr=udp://tracker.bittor.pw:1337/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.opentrackr.org:1337/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.dler.org:6969/announce%20%20%20%20%20%20%20%20&tr=udp://open.stealth.si:80/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.torrent.eu.org:451/announce%20%20%20%20%20%20%20%20&tr=udp://exodus.desync.com:6969/announce%20%20%20%20%20%20%20%20&tr=udp://open.demonii.com:1337/announce"
      echo "Uploading files to Pixeldrain..."

      find Squid* -type f | while read file; do
        echo "Uploading $file..."
        curl -T "$file" -u :876e1688-ae8f-4f30-85ce-42a7749802d9 https://pixeldrain.com/api/file/
      done
