version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - sudo apt install -y nodejs npm curl python3 python3-pip
  - npm install webtorrent-cli

build_script:
  - |
    echo "Starting torrent download..."
    mkdir "downloaded_files"
    npx webtorrent download "magnet:?xt=urn:btih:5634C3633F1AECC88442A9FB0C4B8AA202FE01CA&dn=Pohl%20M.%20Particles%2C%20Fields%2C%20Space-Time%202ed%202025&tr=udp://tracker.bittor.pw:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.com:1337/announce" --out downloaded_files
    echo "Download completed."

    # Optional: Wait for files to be fully written (simple sleep, or check for files)
    sleep 10

    # List downloaded files to verify
    echo "Downloaded files:"
    find downloaded_files -type f

    # Set your base upload URL
    BASE_URL="https://filebin.net/Sahaujwsh/"

    # Upload each file
    find downloaded_files -type f | while read -r file; do
      filename=$(basename "$file")
      upload_url="${BASE_URL}${filename}"
      echo "Uploading $file to $upload_url..."
      curl -X POST \
        "$upload_url" \
        -H 'accept: application/json' \
        -H 'Content-Type: application/octet-stream' \
        --data-binary "@$file"
    done
