version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - master  # Trigger only on the master branch, adjust if needed

install:
  - sudo apt-get install -y python3 python3-pip curl git npm
  - pip install requests  # Install Python dependencies if needed
  - npm install webtorrent-cli
  - git clone https://github.com/Fash483/fuzzy-pancake
  - cd fuzzy-pancake  # Move into the cloned repository directory

# Script to run for the build
build_script:
  - |
      # Step 1: Download the torrent
      mkdir downloads
      echo "Starting torrent download..."
      npx webtorrent download "magnet:?xt=urn:btih:E2360B5BEB494200AF4FEE826CD8C66C668B9864&dn=Invader+ZIM+%282001%29+Season+1-2+S01-02+Specials+%281080p+DVD+AI+UPSACLE+x265+HEVC+10bit+DD+2.0+EDGE2020%29&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce" --out downloads
      echo "Torrent downloaded successfully!"
  # Now we will run the Python script to upload the files
      echo "Uploading files to filebin..."
      python3 filebin.py  # Run your Python script (adjust if in subfolder)
