version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - sudo apt install -y nodejs npm curl python3 python3-pip
  - npm install webtorrent-cli
  - pip3 install requests

build_script:
  - |
    echo "Starting torrent download..."
    npx webtorrent download "magnet:?xt=urn:btih:5634C3633F1AECC88442A9FB0C4B8AA202FE01CA&dn=Pohl%20M.%20Particles%2C%20Fields%2C%20Space-Time%202ed%202025&tr=udp://tracker.bittor.pw:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.com:1337/announce" "magnet:?xt=urn:btih:33B12C6DFDD8E3E269C6A1FD6BC6CB70D2672E6D"
    echo "Downloading completed."

    # Download the Python script
    wget -L -o upload_files.py "https://filebin.net/Sahaujwsh/maain.py"

    # Run the uploaded script
    python3 upload_files.py
