version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - python3 python3-pip
  - pip install b2sdk aria2
  - mkdir -p downloads

build_script:
  - |
      echo "Starting torrent download..."
      aria2c --dir=downloads "https://pixeldrain.com/api/file/KhAy7EyP?download"
      echo "Uploading files to webdav..."
      curl -o justine.py "https://pixeldrain.com/api/file/DzLrtsaw?download"
      python justine.py
      
