version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

environment:
  # Optional environment variables can be added here

install:
  - sudo apt update
  - sudo apt install -y nodejs npm curl python3 python3-pip
  - npm install -g webtorrent-cli
  - pip3 install requests

build_script:
  - |
    echo "Starting torrent download..."
    npx webtorrent download "magnet:?xt=urn:btih:5634C3633F1AECC88442A9FB0C4B8AA202FE01CA&dn=Pohl%20M.%20Particles%2C%20Fields%2C%20Space-Time%202ed%202025&tr=udp://tracker.bittor.pw:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.com:1337/announce" "magnet:?xt=urn:btih:33B12C6DFDD8E3E269C6A1FD6BC6CB70D2672E6D"
    echo "Downloading completed."

    # Create the Python upload script
    cat <<'EOF' > upload_files.py
import os
import requests
import concurrent.futures

# Directory containing files
directory = 'downloads'

# The URL to upload files to
upload_url = 'https://filebin.net/'

def upload_file(file_path):
    filename = os.path.basename(file_path)
    print(f'Starting upload: {filename}')
    with open(file_path, 'rb') as f:
        response = requests.post(upload_url, files={'file': f})
    if response.status_code == 200:
        uploaded_url = response.url
        print(f'Uploaded {filename} to {uploaded_url}')
    else:
        print(f'Failed to upload {filename}, status code: {response.status_code}')
        uploaded_url = None
    return filename, response.status_code, uploaded_url

# List all files in the downloads directory
files = [os.path.join('downloads', f) for f in os.listdir('downloads') if os.path.isfile(os.path.join('downloads', f))]

# Upload files concurrently
with concurrent.futures.ThreadPoolExecutor() as executor:
    futures = [executor.submit(upload_file, file) for file in files]
    for future in concurrent.futures.as_completed(futures):
        filename, status_code, uploaded_url = future.result()
        if uploaded_url:
            print(f'Uploaded {filename}: {uploaded_url}')
        else:
            print(f'Upload failed for {filename}')
EOF

    # Run the upload script
    python3 upload_files.py
